language: cpp
dist: trusty
sudo: false

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-6']
    env: COMPILER=g++-6
  - os: linux
    compiler: clang
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
        packages: ['clang-4.0', 'libstdc++-4.9-dev']
    env: COMPILER=clang++-4.0
  - os: osx
    osx_image: xcode8.3
    compiler: clang
    env: COMPILER=clang++

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - echo ${PATH}
  - cmake --version
  - export CXX=${COMPILER}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v

script:
  - ./deps.sh
  - mkdir -p build && cd build
  - cmake .. && make -j4
  - CTEST_OUTPUT_ON_FAILURE=1 make test
